### ISSUE TITLE
Behavior of ; after F or T

### ISSUE THREAD

**Issue by morganprecision** [svermeulen/vim-NotableFt#1]
I'm really liking this plugin ... the only thing I'm having trouble adjusting to is the behavior of `;` after hitting `F` or `T`. Following the native behavior of Vim, it seems like `;` should move to the next match backwards instead of the next match forward after hitting `F` or `T`.

Thanks for sharing this plugin with the community.

**Comment by svermeulen** [comment]
Ah yeah, forgot that I changed that.  I prefer having ; and , always go in a consistent direction
I'll make an option for that though and make vim's behaviour the default

**Comment by svermeulen** [comment]
Ok I've fixed this to use vim's normal behaviour by default.  And added option for those people like me that prefer the other way
