### ISSUE TITLE
Don't hijack the search

### ISSUE THREAD

**Issue by AndrewRayCode** [svermeulen/vim-NotableFt#2]
Using this plugin replaces my current search query and turns on search highlighting when I use it. The user's search settings shouldn't be modified during the use of this plugin.

**Comment by svermeulen** [comment]
Sorry I'm not sure what you mean.  It shouldn't replace the search query that you use with `/` and `?`.  Eg: Hitting `n` will search different pattern than hitting `;`.

It does highlight the characters that it's using for its own search, but shouldn't affect the highlight used with `/` and `?`.  Can you elaborate on the problem you're seeing?

**Comment by AndrewRayCode** [comment]
Oh I see, it only highlights the characters found, which to me looked like it was changing my search pattern. My mistake.

**Comment by svermeulen** [comment]
Yeah, it uses the same highlight style as normal search.  Now that you mention it though, it might be useful to (optionally) use a different one to differentiate the two search methods.
